items_db = [
    {
        "id": "item_001",
        "title": "Vintage Leather Jacket",
        "description": "Classic brown leather jacket, early 90s. Buttery soft leather with a perfect patina. YKK zippers, quilted lining, and that worn-in feel you can't fake.",
        "image_url": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80",
        "price": "$185",
        "source": "Depop",
        "source_url": "https://www.depop.com/products/example-vintage-leather-jacket-90s",
        "category": "Outerwear",
        "tags": ["vintage", "leather", "90s", "brown", "motorcycle"],
        "likes": 47,
        "curator": "alex.curates"
    },
    {
        "id": "item_002",
        "title": "Wide Leg Jeans",
        "description": "Y2K wide leg denim in a light wash. High rise with raw hem. Made in Italy, early 2000s. Baggy fit through the leg.",
        "image_url": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80",
        "price": "$65",
        "source": "Vinted",
        "source_url": "https://www.vinted.co.uk/items/example-wide-leg-jeans-y2k",
        "category": "Bottoms",
        "tags": ["y2k", "denim", "wide-leg", "light-wash", "italian"],
        "likes": 32,
        "curator": "vintage.vibes"
    },
    {
        "id": "item_003",
        "title": "Silk Slip Dress",
        "description": "90s-inspired slip dress in champagne silk charmeuse. Adjustable spaghetti straps, cowl neck, side slit. Lined body, unlined skirt.",
        "image_url": "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&q=80",
        "price": "$120",
        "source": "Grailed",
        "source_url": "https://www.grailed.com/listings/example-silk-slip-dress-90s",
        "category": "Dresses",
        "tags": ["silk", "slip-dress", "90s", "champagne", "cowl-neck"],
        "likes": 28,
        "curator": "alex.curates"
    },
    {
        "id": "item_004",
        "title": "Cashmere Crew Neck",
        "description": "Soft grey cashmere crewneck sweater. Minimalist, pre-loved, like new. Two-ply Scottish cashmere, ribbed cuffs and hem. Size M.",
        "image_url": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80",
        "price": "$89",
        "source": "Depop",
        "source_url": "https://www.depop.com/products/example-cashmere-crewneck-grey",
        "category": "Tops",
        "tags": ["cashmere", "minimalist", "grey", "sweater", "scottish"],
        "likes": 19,
        "curator": "minimal.style"
    },
    {
        "id": "item_005",
        "title": "Platform Loafers",
        "description": "Chunky platform loafers in black leather. 70s-inspired silhouette with a 2-inch platform. Crepe sole, horsebit detail. Euro size 39.",
        "image_url": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80",
        "price": "$55",
        "source": "Vinted",
        "source_url": "https://www.vinted.co.uk/items/example-platform-loafers-70s",
        "category": "Shoes",
        "tags": ["platform", "loafers", "70s", "chunky", "vintage"],
        "likes": 41,
        "curator": "retro.foot"
    },
    {
        "id": "item_006",
        "title": "Denim Jacket",
        "description": "Vintage Levi's Type III trucker jacket. 90s made in USA. Big E red tab, copper buttons, light stonewash. Some fade marks, all character.",
        "image_url": "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&q=80",
        "price": "$95",
        "source": "Grailed",
        "source_url": "https://www.grailed.com/listings/example-levis-type-iii-trucker",
        "category": "Outerwear",
        "tags": ["denim", "levis", "trucker", "vintage", "usa-made"],
        "likes": 56,
        "curator": "denim.head"
    },
    {
        "id": "item_007",
        "title": "Printed Midi Skirt",
        "description": "Floral print midi skirt with full lining. Elastic waistband with drawstring, flowy viscose cut. Pockets! Fun 90s Laura Ashley print revival.",
        "image_url": "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&q=80",
        "price": "$45",
        "source": "Depop",
        "source_url": "https://www.depop.com/products/example-floral-midi-skirt",
        "category": "Bottoms",
        "tags": ["floral", "midi", "printed", "flowy", "pockets"],
        "likes": 24,
        "curator": "vintage.vibes"
    },
    {
        "id": "item_008",
        "title": "Trench Coat",
        "description": "Classic beige trench coat by Burberry. Double breasted, belted waist, epaulettes. Timeless piece in excellent condition. Size UK 10.",
        "image_url": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80",
        "price": "$150",
        "source": "Vinted",
        "source_url": "https://www.vinted.co.uk/items/example-burberry-trench-coat",
        "category": "Outerwear",
        "tags": ["trench", "beige", "classic", "timeless", "burberry"],
        "likes": 38,
        "curator": "minimal.style"
    },
    {
        "id": "item_009",
        "title": "Striped Oxford Shirt",
        "description": "Blue and white striped oxford cloth button-down. Ralph Lauren, cotton, pre-owned with excellent condition. OCBD collar, chest pocket. Size L.",
        "image_url": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80",
        "price": "$35",
        "source": "Depop",
        "source_url": "https://www.depop.com/products/example-striped-oxford-shirt",
        "category": "Tops",
        "tags": ["striped", "oxford", "cotton", "preppy", "ralph-lauren"],
        "likes": 15,
        "curator": "alex.curates"
    },
    {
        "id": "item_010",
        "title": "Leather Crossbody Bag",
        "description": "Mini leather crossbody in cognac. Gold hardware, adjustable strap, three interior card slots. Beautiful aged patina developing. By Coach, 90s.",
        "image_url": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80",
        "price": "$78",
        "source": "Grailed",
        "source_url": "https://www.grailed.com/listings/example-coach-leather-crossbody",
        "category": "Accessories",
        "tags": ["leather", "crossbody", "cognac", "mini", "coach"],
        "likes": 63,
        "curator": "retro.foot"
    },
    {
        "id": "item_011",
        "title": "Chunky Knit Cardigan",
        "description": "Oversized cream cardigan in chunky cable knit. Mother of pearl buttons, deep ribbed cuffs. Coziest thing you'll own this winter. Hand wash only.",
        "image_url": "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&q=80",
        "price": "$72",
        "source": "Vinted",
        "source_url": "https://www.vinted.co.uk/items/example-chunky-knit-cardigan",
        "category": "Tops",
        "tags": ["chunky", "cardigan", "cream", "cozy", "cable-knit"],
        "likes": 34,
        "curator": "cozy.vibes"
    },
    {
        "id": "item_012",
        "title": "High Waist Shorts",
        "description": "Denim high waist shorts, cutoff style. Frayed hem, relaxed fit through the leg. 90s Levi's cutoffs. Button fly, 5-pocket styling.",
        "image_url": "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&q=80",
        "price": "$38",
        "source": "Depop",
        "source_url": "https://www.depop.com/products/example-levis-high-waist-shorts",
        "category": "Bottoms",
        "tags": ["denim", "shorts", "high-waist", "cutoff", "summer"],
        "likes": 21,
        "curator": "vintage.vibes"
    },
    {
        "id": "item_013",
        "title": "Leather Chelsea Boots",
        "description": "Classic black Chelsea boots in smooth leather. Sleek silhouette, side elastic panels, pull tab. Blake stitched sole. Euro size 41.",
        "image_url": "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=600&q=80",
        "price": "$110",
        "source": "Grailed",
        "source_url": "https://www.grailed.com/listings/example-chelsea-boots-black",
        "category": "Shoes",
        "tags": ["chelsea", "boots", "black", "leather", "classic"],
        "likes": 45,
        "curator": "retro.foot"
    },
    {
        "id": "item_014",
        "title": "Bomber Jacket",
        "description": "Olive green MA-1 bomber jacket. Nylon shell with water-resistant finish. Ribbed cuffs and hem, removable hood. 90s surplus style, modern condition.",
        "image_url": "https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=600&q=80",
        "price": "$88",
        "source": "Vinted",
        "source_url": "https://www.vinted.co.uk/items/example-bomber-jacket-ma-1",
        "category": "Outerwear",
        "tags": ["bomber", "olive", "military", "90s", "ma-1"],
        "likes": 29,
        "curator": "denim.head"
    },
    {
        "id": "item_015",
        "title": "Velvet Blazer",
        "description": "Rich burgundy velvet blazer. Notched satin lapels, single button closure, flap pockets. Perfect for holiday parties or a sharp night out. Size M.",
        "image_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
        "price": "$95",
        "source": "Depop",
        "source_url": "https://www.depop.com/products/example-velvet-blazer-burgundy",
        "category": "Outerwear",
        "tags": ["velvet", "blazer", "burgundy", "vintage", "evening"],
        "likes": 37,
        "curator": "alex.curates"
    },
    {
        "id": "item_016",
        "title": "Tartan Mini Skirt",
        "description": "Authentic Vivienne Westwood tartan mini. Red and black MacLeod pattern. Adjustable waist, pleated back, center zip. Early 2000s archive piece.",
        "image_url": "https://images.unsplash.com/photo-1602293589930-45aad59ba9c3?w=600&q=80",
        "price": "$210",
        "source": "Grailed",
        "source_url": "https://www.grailed.com/listings/example-vivienne-westwood-tartan",
        "category": "Bottoms",
        "tags": ["tartan", "vivienne-westwood", "mini", "pleated", "archive"],
        "likes": 71,
        "curator": "archive.angel"
    },
    {
        "id": "item_017",
        "title": "Mohair Sweater",
        "description": "Fuzzy pink mohair blend sweater. 80s original, sheer and soft. Oversized fit, balloon sleeves. Statement piece in amazing condition.",
        "image_url": "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
        "price": "$58",
        "source": "Depop",
        "source_url": "https://www.depop.com/products/example-mohair-sweater-pink",
        "category": "Tops",
        "tags": ["mohair", "pink", "80s", "oversized", "fuzzy"],
        "likes": 43,
        "curator": "archive.angel"
    },
    {
        "id": "item_018",
        "title": "Cargo Pants",
        "description": "Y2K nylon cargo pants in khaki. Multiple zip pockets, adjustable cuffs, drawstring waist. Techwear before techwear was a thing. Size S.",
        "image_url": "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80",
        "price": "$48",
        "source": "Vinted",
        "source_url": "https://www.vinted.co.uk/items/example-cargo-pants-y2k",
        "category": "Bottoms",
        "tags": ["cargo", "y2k", "khaki", "techwear", "nylon"],
        "likes": 36,
        "curator": "street.park"
    },
    {
        "id": "item_019",
        "title": "Suede Fringe Jacket",
        "description": "70s suede fringe jacket in caramel brown. Leather tie closures, embroidered yoke, fully lined. Perfect festival piece. Size M.",
        "image_url": "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600&q=80",
        "price": "$165",
        "source": "Depop",
        "source_url": "https://www.depop.com/products/example-suede-fringe-jacket",
        "category": "Outerwear",
        "tags": ["suede", "fringe", "70s", "festival", "caramel"],
        "likes": 52,
        "curator": "vintage.vibes"
    },
    {
        "id": "item_020",
        "title": "Gold Hoop Earrings",
        "description": "Vintage 14k gold filled hoop earrings. 1.5 inch diameter, hinged closure. Subtle hammered texture. Light everyday wear throughout.",
        "image_url": "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&q=80",
        "price": "$42",
        "source": "Depop",
        "source_url": "https://www.depop.com/products/example-gold-hoop-earrings",
        "category": "Accessories",
        "tags": ["gold", "hoops", "vintage", "minimal", "everyday"],
        "likes": 29,
        "curator": "minimal.style"
    },
    {
        "id": "item_021",
        "title": "Polo Shirt",
        "description": "Vintage Ralph Lauren polo in navy. Classic pique cotton, embroidered pony, ribbed collar. 90s made in USA. Perfect preppy staple. Size L.",
        "image_url": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80",
        "price": "$32",
        "source": "Grailed",
        "source_url": "https://www.grailed.com/listings/example-ralph-lauren-polo",
        "category": "Tops",
        "tags": ["polo", "ralph-lauren", "navy", "preppy", "usa"],
        "likes": 18,
        "curator": "alex.curates"
    },
    {
        "id": "item_022",
        "title": "Leather Combat Boots",
        "description": "Doc Martens 1460 smooth leather boots in cherry red. Classic 8-eye silhouette, yellow stitching, air-cushion sole. Some wear, tons of life left. UK 7.",
        "image_url": "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&q=80",
        "price": "$75",
        "source": "Vinted",
        "source_url": "https://www.vinted.co.uk/items/example-doc-martens-1460",
        "category": "Shoes",
        "tags": ["doc-martens", "combat", "cherry-red", "8-eye", "vintage"],
        "likes": 67,
        "curator": "street.park"
    },
    {
        "id": "item_023",
        "title": "Silk Scarf",
        "description": "Hermes silk twill scarf in the 'Brides de Gala' pattern. 90cm square, hand-rolled edges. Rich burgundy and navy colorway. 1990s.",
        "image_url": "https://images.unsplash.com/photo-1606768666853-403c90c981d6?w=600&q=80",
        "price": "$195",
        "source": "Grailed",
        "source_url": "https://www.grailed.com/listings/example-hermes-silk-scarf",
        "category": "Accessories",
        "tags": ["hermes", "silk", "scarf", "luxury", "90s"],
        "likes": 44,
        "curator": "archive.angel"
    },
    {
        "id": "item_024",
        "title": "Corduroy Shirt Jacket",
        "description": "Wide wale corduroy shirt jacket in mustard yellow. Snap buttons, two chest pockets, blanket lined. 70s Pendleton. Rugged and warm. Size L.",
        "image_url": "https://images.unsplash.com/photo-1604644401890-0bd678c83788?w=600&q=80",
        "price": "$82",
        "source": "Depop",
        "source_url": "https://www.depop.com/products/example-corduroy-shirt-jacket",
        "category": "Outerwear",
        "tags": ["corduroy", "mustard", "pendleton", "70s", "shirt-jacket"],
        "likes": 31,
        "curator": "cozy.vibes"
    },
    {
        "id": "item_025",
        "title": "Knit Vest",
        "description": "Argyle pattern knit vest in navy and cream. V-neck, ribbed hem and armholes. 80s preppy staple. Wool blend, excellent condition. Size S.",
        "image_url": "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&q=80",
        "price": "$28",
        "source": "Vinted",
        "source_url": "https://www.vinted.co.uk/items/example-argyle-knit-vest",
        "category": "Tops",
        "tags": ["argyle", "vest", "preppy", "80s", "wool"],
        "likes": 14,
        "curator": "minimal.style"
    },
    {
        "id": "item_026",
        "title": "Tote Bag",
        "description": "Canvas tote bag with leather bottom and handles. Natural undyed canvas, cognac leather trim. Roomy interior, interior zip pocket. Handmade in Tokyo.",
        "image_url": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80",
        "price": "$65",
        "source": "Grailed",
        "source_url": "https://www.grailed.com/listings/example-canvas-tote-bag",
        "category": "Accessories",
        "tags": ["canvas", "tote", "leather", "japanese", "minimal"],
        "likes": 25,
        "curator": "minimal.style"
    },
    {
        "id": "item_027",
        "title": "Ribbed Knit Dress",
        "description": "Bodycon ribbed knit dress in chocolate brown. Long sleeves, mock neck, midi length. Hugs in all the right places. Size S, like new.",
        "image_url": "https://images.unsplash.com/photo-1581044777550-4c8a0c1b1e1f?w=600&q=80",
        "price": "$55",
        "source": "Depop",
        "source_url": "https://www.depop.com/products/example-ribbed-knit-dress",
        "category": "Dresses",
        "tags": ["ribbed", "brown", "midi", "bodycon", "minimal"],
        "likes": 39,
        "curator": "cozy.vibes"
    },
    {
        "id": "item_028",
        "title": "Track Jacket",
        "description": "Vintage Adidas Firebird track jacket. Classic 3-stripe design in royal blue and white. Shell fabric, stand-up collar. 80s West German made.",
        "image_url": "https://images.unsplash.com/photo-1608236415051-3b5566a0a3c5?w=600&q=80",
        "price": "$68",
        "source": "Vinted",
        "source_url": "https://www.vinted.co.uk/items/example-adidas-firebird-jacket",
        "category": "Outerwear",
        "tags": ["adidas", "track-jacket", "80s", "vintage", "3-stripe"],
        "likes": 58,
        "curator": "street.park"
    },
    {
        "id": "item_029",
        "title": "Patent Leather Heels",
        "description": "Black patent leather pumps by Manolo Blahnik. Pointed toe, 3-inch stiletto heel. Minimalist and deadly. Worn once, impeccable. Size 38.",
        "image_url": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80",
        "price": "$145",
        "source": "Grailed",
        "source_url": "https://www.grailed.com/listings/example-manolo-blahnik-pumps",
        "category": "Shoes",
        "tags": ["patent", "heels", "manolo-blahnik", "black", "evening"],
        "likes": 48,
        "curator": "archive.angel"
    },
    {
        "id": "item_030",
        "title": "Grandpa Cardigan",
        "description": "Brown herringbone tweed cardigan. Horn buttons, leather elbow patches, two lower patch pockets. Feels like a hug from your grandad. Size XL (fits M-L oversized).",
        "image_url": "https://images.unsplash.com/photo-1608215559241-3b1d5f4c9a4e?w=600&q=80",
        "price": "$62",
        "source": "Depop",
        "source_url": "https://www.depop.com/products/example-tweed-grandpa-cardigan",
        "category": "Tops",
        "tags": ["tweed", "cardigan", "grandpa", "herringbone", "cozy"],
        "likes": 33,
        "curator": "cozy.vibes"
    },
]

boards_db = [
    {
        "id": "board_001",
        "name": "90s Archive",
        "curator": "alex.curates",
        "description": "The best of 90s fashion — leather, denim, and silk. Pieces that defined a decade.",
        "items": ["item_001", "item_003", "item_006", "item_009"],
        "item_count": 4
    },
    {
        "id": "board_002",
        "name": "Capsule Minimal",
        "curator": "minimal.style",
        "description": "Clean lines, neutral tones. Timeless pieces that last beyond trends.",
        "items": ["item_004", "item_008", "item_010", "item_020", "item_026"],
        "item_count": 5
    },
    {
        "id": "board_003",
        "name": "Streetwear Finds",
        "curator": "denim.head",
        "description": "Denim, bombers, and boots. Curated street style that actually works.",
        "items": ["item_006", "item_013", "item_014", "item_028"],
        "item_count": 4
    },
    {
        "id": "board_004",
        "name": "Archive Angels",
        "curator": "archive.angel",
        "description": "Designer archive pieces and rare vintage finds. For collectors and enthusiasts.",
        "items": ["item_016", "item_017", "item_023", "item_029"],
        "item_count": 4
    },
    {
        "id": "board_005",
        "name": "Cozy Hours",
        "curator": "cozy.vibes",
        "description": "The softest knits, warmest jackets, and most comfortable fits for slow days.",
        "items": ["item_011", "item_024", "item_027", "item_030"],
        "item_count": 4
    },
]

items = {item["id"]: item for item in items_db}
boards = {board["id"]: board for board in boards_db}
